on:
  push:
  pull_request:

name: test

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Create Conda environment
        run: conda env create -f liana_env.yml

      - name: Initialize Conda on shell
        run: conda init bash

      - name: Source conda.sh
        #run: source $(echo $(which conda) | rev | cut -d'/' -f3- | rev)/etc/profile.d/conda.sh
        run: source $(which conda/etc/profile.d/conda.sh

      - name: Activate Conda environment
        run: conda activate liana_env

      - name: Configure homer
        run: perl  $(echo $(which conda) | rev | cut -d'/' -f3- | rev)/envs/liana_envs/share/homer*/configureHomer.pl -install mm10

      - name: Download promoter annotations
        run: perl $(echo $(which conda) | rev | cut -d'/' -f3- | rev)/envs/liana_env/share/homer*/configureHomer.pl -install mouse-p

      - name: Verify pipeline works
        run: nextflow run liana.nf --help

      - name: Run pipeline works
        run: nextflow run liana.nf --bed2D example_files/bed2D.bed  --genome mm10 --peaks example_files/peaks.txt
