# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: test

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Nextflow
        run: wget -qO- https://get.nextflow.io | bash

      - name: Nextflow is executable
        run: chmod +x nextflow

      - name: Verify Nextflow is installed
        run: ./nextflow help

      - name: Create Conda environment
        run: conda create -f liana_env.yaml

      - name: Activate Conda environment
        run: conda activate liana_env

      - name: Configure homer
        run: perl $(which conda)/envs/plac_anno_env/share/homer*/configureHomer.pl -install mm10

      - Download promoter annotations
        run: perl $(which conda)/envs/plac_anno_env/share/homer*/configureHomer.pl -install human-p

      - name: Launch pipeline
        run: nextflow run liana.nf --help

